#!/bin/bash

export WORKSPACE="/root/iotivity"

cd $WORKSPACE

#if [ ! -d "${WORKSPACE}/extlibs/boost" ]
#then
#    mkdir ${WORKSPACE}/extlibs/boost
#fi
#
#if [ ! -d "${WORKSPACE}/extlibs/gtest" ]
#then
#mkdir ${WORKSPACE}/extlibs/gtest
#fi

ln -sv ${ANDROID_NDK} ${WORKSPACE}/extlibs/android/ndk/android-ndk-r10d
ln -sv ${ANDROID_HOME} ${WORKSPACE}/extlibs/android/sdk/android-sdk_r24.2
# ln -sv  /usr/local/mbedtls extlibs/mbedtls/mbedtls
#ln -sv ${IOTIVITYEXTLIB}/android/gradle-2.2.1 ${WORKSPACE}/extlibs/android/gradle/gradle-2.2.1
#ln -sv ${IOTIVITYEXTLIB}/expat/expat-2.1.0 ${WORKSPACE}/extlibs/expat/expat-2.1.0
#ln -sv ${IOTIVITYEXTLIB}/gtest/gtest-1.7.0 ${WORKSPACE}/extlibs/gtest/gtest-1.7.0
#ln -sv ${IOTIVITYEXTLIB}/hippomocks-master ${WORKSPACE}/extlibs/hippomocks-master
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/
export JAVA_LIB=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/

./auto_build.sh  android

#rm -rf /root/extlibs/boost/boost_1_58_0/ 

#clean symlinks
cd ${WORKSPACE}/extlibs/
find . -maxdepth 1 -type l -exec rm -f {} \;

